name: Update Random Waifu

on:
  schedule:
    - cron: "0 0 * * *"
      timezone: "Asia/Almaty"

  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-waifu:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get random waifu
        run: |
          mkdir -p assets

          RESPONSE=$(curl -s \
            -H "User-Agent: GitHubProfileWaifu (https://github.com/${{ github.repository }})" \
            "https://nekos.best/api/v2/waifu")

          IMAGE_URL=$(echo "$RESPONSE" | jq -r '.results[0].url')

          echo "Downloading: $IMAGE_URL"

          curl -L "$IMAGE_URL" -o assets/waifu.png

      - name: Commit new waifu
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add assets/waifu.png

          if git diff --cached --quiet; then
            echo "Nothing changed"
            exit 0
          fi

          git commit -m "chore: update random waifu"
          git push